name: Check
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout actions
      uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gidgethub
        pip install aiohttp

    - name: 
      env:
        PEM_FILE_PATH: ${{ secrets.PEM_FILE_PATH }}
        GH_AUTH: ${{ secrets.GH_AUTH }}
        GH_SECRET: ${{ secrets.GH_SECRET }}
        GH_APP_ID: ${{ secrets.GH_APP_ID }}
      run: |
        pwd
        ls -l
        cd webservice
        python template.py
